### ISSUE TITLE
Readme says DX11 only but it works in metal mac editor.

### ISSUE THREAD

**Issue by SteveElbows** [Unity-Technologies/VolumetricLighting#13]
Title says it all really, seems to work fine for me with Unity 5.6 when I switch on metal editor support :)

**Comment by jknightdoeswork** [comment]
Doesn't work for me. I get an all pink Metal Unity Editor in 2017.2 and in 5.6.0f3 I get 
```
Metal: Shader[Hidden/BlurShadowmap]: Pixel format [MTLPixelFormatDepth32Float_Stencil8] of texture [AreaLight Shadowmap] bound at index 0 is incompatible with texture parameter [half _Shadowmap]. Compatible types [float]
```

Warning in the logs.

I'm on OSX El Capitan. Might need to update my OS.

**Comment by rsodre** [comment]
Tested yesterday on OSX metal and not working either

**Comment by robertcupisz** [comment]
Thanks @SteveElbows!

@jknightdoeswork Might be out of date drivers indeed.

@rsodre Are you sure you were running metal? There's an extra checkbox to enable metal support in the editor, only then will it say 'metal' in Unity's title bar. Please try again with the latest from this repo, it spits out some extra info now.

**Comment by jknightdoeswork** [comment]
Means a lot to me that you responded in good time, @robertcupisz.

Can you give me guidance on what is required to allow the project to run on OpenGL on a Mac?

**Comment by robertcupisz** [comment]
@jknightdoeswork The effect needs compute shaders, so Apple would have to add opengl 4.3 support to mac, which won't happen any time soon, I'm afraid.

**Comment by rsodre** [comment]
Found the metal flag, and it works :)
