### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rsodre** [Unity-Technologies/VolumetricLighting#15]
Do this effect has any future, or will remain just as a demo?
Integrating to the post processing stack?
Support for non DX11 apis?
Please say you'll be releasing it in the stack!

**Comment by robertcupisz** [comment]
Yeap, I'll keep developing for the upcoming demos. Features include more light types supported, better and softer shadows, lots of control over fog density and its animation, etc.

It'll be integrated in the post processing stack (but remain a separate repo).

It will also be tightly integrated with the HD render pipeline from the ScriptableRenderPipelines project, for better or for worse ;)

For now I will only intentionally support platforms that are required by the upcoming demos, which are tbd. There's a good chance the effect works on other platforms supporting compute shaders. I've tested it today on dx12 and osx metal as well.
