### ISSUE TITLE
Unity 2017.2.0p2 Cannot Build App Due to Shader Compliation Errors

### ISSUE THREAD

**Issue by davon92** [Unity-Technologies/VolumetricLighting#22]
The Hidden/ApplyToOpaque.shader / VolumetricFog.cging could not compile due to not supporting bitwise operations on pragma target 3.0. setting target to something higher like pragma target 5.0 removes the error

Location of Error: 
VolumetricFog.cginc
Line 9;  n = (n<<13)^n;
These two are connected
ApplyToOpaque.shader 
Line 8:  #pragma target 3.0

The Hidden Hidden/BlurShadowmap Fails twice due to D3D9 not supporting seperate texture+sampler State HLSL Syntax.

Location of Error: 
BlurShadowmap.shader 
Line 70:  z.r = _ShadowmapDummy.Sample(sampler_ShadowmapDummy, 0).a;

Image of Errors:
![build error shader](https://user-images.githubusercontent.com/14450984/33770249-e8fd0f22-dbfa-11e7-9a30-d81041efd404.PNG)

**Comment by Kafalkhor** [comment]
same problem

**Comment by robertcupisz** [comment]
This effect won't run on d3d9, it needs compute shaders, sorry.
