### ISSUE TITLE
I cant understand the Shader 、ComputeShader how to defined with "HideInInspector" in this project

### ISSUE THREAD

**Issue by losuffi** [Unity-Technologies/VolumetricLighting#25]
Example ： VolumetircFog——ComputeShader——m_Scatter。 The Code Working Well。But I Cant Rename the Variable Name，It will throw NullRef。I want to know the m_Scatter
 how to defined . others like it?

**Comment by robertcupisz** [comment]
If you select the VolumetricFog.cs script in the project view, the inspector shows the compute shader that m_Scatter is referencing.

Also this is handy for renaming serialized properties:
https://docs.unity3d.com/ScriptReference/Serialization.FormerlySerializedAsAttribute.html
