### ISSUE TITLE
Unity 2018.1.0f2 - Property (_PointLights) at kernel index (0) is not set

### ISSUE THREAD

**Issue by Propagant** [Unity-Technologies/VolumetricLighting#26]
Just got stucked in `Property (_PointLights) at kernel index (0) is not set`
Any idea devs?

**Comment by AlexanderBalson** [comment]
Getting the same problem, not sure how to fix it without ruining everything. Please help, someone with the skills!

**Comment by danilonobren** [comment]
sam here

**Comment by corybarr** [comment]
I got around the issue by first loading and running the scene "Tube lights and local fog density." Something in that scene sets the property. Then the other scenes ran without the error.

**Comment by hifar** [comment]
same error please help!

**Comment by hifar** [comment]
Is there anyone solved this issue?

**Comment by robertcupisz** [comment]
Fixed!
