### ISSUE TITLE
Compute shader property issue with 2018.2.4f1

### ISSUE THREAD

**Issue by transat** [Unity-Technologies/VolumetricLighting#28]
After upgrading to 2018.2.4f1 I get the following error in the console:

> Compute shader (InjectLightingAndDensity): Property (_AreaLightShadowmap) at kernel index (0) is not set
> UnityEngine.ComputeShader:Dispatch(ComputeShader, Int32, Int32, Int32, Int32)
> VolumetricFog:Scatter() (at Assets/VolumetricLighting/Assets/VolumetricFog/Scripts/VolumetricFog.cs:512)
> VolumetricFog:OnRenderImage(RenderTexture, RenderTexture) (at Assets/VolumetricLighting/Assets/VolumetricFog/Scripts/VolumetricFog.cs:559)

**Comment by maxsamarin** [comment]
Same issue

**Comment by LJHhahaha** [comment]
me too

**Comment by LJHhahaha** [comment]
aha，I found it，you should first open AreaLight scene，then open other scene，but，i am thinking， if i package it out should i must enter arealight scene then enter other scene？

**Comment by LJHhahaha** [comment]
another way：set the Area light gameobject on in the tube light Scene, this is not the correct solution,  but no error report, Iguess this problem exist at start, otherwise there can not be a area light in tube light scene.

**Comment by robcupisz** [comment]
Fixed in latest

**Comment by maxsamarin** [comment]
> Fixed in latest

Thank you!
