### ISSUE TITLE
"VolumetricFog requires compute shaders to run, disabling"

### ISSUE THREAD

**Issue by ranajitdas33** [Unity-Technologies/VolumetricLighting#3]
![screenshot_1](https://cloud.githubusercontent.com/assets/6286184/23328801/68be1fc6-fb50-11e6-99b1-eeffcb1162bc.jpg)

I am getting an error. "VolumetricFog requires compute shaders to run, disabling" And no volumetric fog is being displayed.

![screenshot_3](https://cloud.githubusercontent.com/assets/6286184/23328796/62565efa-fb50-11e6-9c4e-6db011949305.jpg)

**Comment by robertcupisz** [comment]
The effect does need compute shaders to run - system requirements on the main page mention DX11.

**Comment by ranajitdas33** [comment]
Thanks. I actually figured it out its because of DX11. and ur correct. Thanks again.
