### ISSUE TITLE
Unable to use volumetric fog in my scene

### ISSUE THREAD

**Issue by Hurl3y** [Unity-Technologies/VolumetricLighting#30]
Hello, i try to use volumetric fog in my scene but it's not working !
What i do : 
Put volumetric fog script on my camera
put light manager fog light script on an empty game object
put fog light script on my lights
Nothings happens when i hit play 
if anyone can help me that would be really nice !
Thanks, johann.

Edit : there is an error i don't really understand : 

> Compute shader (InjectLightingAndDensity): Property (_AreaLightShadowmap) at kernel index (0) is not set
UnityEngine.ComputeShader:Dispatch(Int32, Int32, Int32, Int32)
VolumetricFog:Scatter() (at Assets/fog/VolumetricFog/Scripts/VolumetricFog.cs:512)
VolumetricFog:OnRenderImage(RenderTexture, RenderTexture) (at Assets/fog/VolumetricFog/Scripts/VolumetricFog.cs:559)

>

**Comment by robcupisz** [comment]
Fixed in latest
