### ISSUE TITLE
Texture area lights?

### ISSUE THREAD

**Issue by zomby138** [Unity-Technologies/VolumetricLighting#31]
Are there any plans to implement textured area lights?

Like this:
https://www.youtube.com/watch?v=hqp7kHPVr58&t=113s

I would like that very much

**Comment by robcupisz** [comment]
Hey, I'm not actively adding features to this code anymore. It has been more or less superseded by Unity's High Definition Render Pipeline and its area lights and fog, which both use the same techniques I used in this project.

But, if anyone would be interested in adding textured area lights to this implementation, it wouldn't be too hard. Area lights here are based on this paper https://eheitzresearch.wordpress.com/415-2/ and the paper also discusses extending them to textured lights.
