### ISSUE TITLE
AreaLight - Far quad matrix is calculated wrong

### ISSUE THREAD

**Issue by enzi** [Unity-Technologies/VolumetricLighting#4]
You can reproduce the effect in the AreaLight scene

![arealightvalues](https://cloud.githubusercontent.com/assets/4227676/23561942/b6ea2c5e-0040-11e7-9a19-8d80cd91d070.PNG)

It seems like the quad to quad projection has a wrong quad as far quad. 
![arealight2](https://cloud.githubusercontent.com/assets/4227676/23561943/b6eaeb44-0040-11e7-9d70-a1d112d89600.PNG)
![arealight3](https://cloud.githubusercontent.com/assets/4227676/23561941/b6e797b4-0040-11e7-9a52-6b5d97df0008.PNG)

The culprit can be found here:
AreaLight.Direct.cs - SetUpCommandBuffer

`Matrix4x4 m = Matrix4x4.TRS(new Vector3(0, 0, 10.0f), Quaternion.identity, Vector3.one * 20);
buf.DrawMesh(m_Cube, t.localToWorldMatrix * m, m_ProxyMaterial, 0, m_Shadows ? /*shadows*/ 0 : /*no shadows*/ 1);`

I changed this to:
`Matrix4x4 m = Matrix4x4.TRS(new Vector3(0, 0, 0), Quaternion.identity, m_Size * 20.0f);
		buf.DrawMesh(m_Cube, t.localToWorldMatrix * m, m_ProxyMaterial, 0, m_Shadows ? /*shadows*/ 0 : /*no shadows*/ 1);`

It fixes the problem but I also have no idea what I really did. Can someone in charge skim over this and fix this properly?

Here's an image with the code change in action:
![arealightfixed](https://cloud.githubusercontent.com/assets/4227676/23562625/8aeb3e10-0043-11e7-9151-d00647b32fd7.PNG)

**Comment by robertcupisz** [comment]
The distance of the far plane (and in the case of disabled shadows - the entire light cube) is just a placeholder. It's waiting for a light falloff function, which pulls the light contribution to 0 at a finite distance. The current falloff is physically based, which means it falls of to 0 at infinity - so your fix only pushes the problem further away.

Anyway, once I come up with a decent finite falloff function, I'll implement it and fix the proxy mesh bounds as well.
