### ISSUE TITLE
Cellnoise - visible noise from far away

### ISSUE THREAD

**Issue by enzi** [Unity-Technologies/VolumetricLighting#5]
Open "Tube lights and local fog density" scene and put the camera to: 
![cameraposition](https://cloud.githubusercontent.com/assets/4227676/23562722/fcbd1c34-0043-11e7-8a84-3650eeeae837.PNG)

You should see this:
![lightnoise](https://cloud.githubusercontent.com/assets/4227676/23562733/0f97ef5a-0044-11e7-838f-576eead01891.PNG)

I could locate the source of this noise which is in VolumetricFog.cginc - Fog function

`uvw.xy += cellNoise(uvw.xy * _Screen_TexelSize.zw) * _VolumeScatter_TexelSize.xy * 0.8;`

This removes the noise but also introducs banding:
`uvw.xy += /*cellNoise(uvw.xy * _Screen_TexelSize.zw) */ _VolumeScatter_TexelSize.xy * 0.8;`

I rewrote the Fog method to also have a time parameter to enable scrolling the cellnoise. With an applied Temporal Anti-Aliasing the results were not bad but still not good enough. The distribution pattern of the cellnoise doesn't seem to help in this problem.
![lightnoisetaa](https://cloud.githubusercontent.com/assets/4227676/23563514/449d83c4-0047-11e7-96a5-3422a97f2374.PNG)

A lot of the problems where talked about in the Inside rendering talk (https://www.youtube.com/watch?v=RdN06E6Xn9E) 
They used a blue noise in the end. Can we also do this?

**Comment by robertcupisz** [comment]
I intentionally introduced the noise to hide banding artifacts (which get more pronounced when there are volumetric shadow edges in view).

I'm very aware of Mikkel's research on the topic and I'll be working on improving banding removal in the coming months, for our current demo.
