### ISSUE TITLE
5.6

### ISSUE THREAD

**Issue by sniffle6** [Unity-Technologies/VolumetricLighting#7]
in unity 5.6.0b9

lights seem to only effect fog and not the geometry, shadows on area lights are messed up. various other small things wrong

**Comment by robertcupisz** [comment]
I've just verified it in 5.6.0b11 and all the scenes look exactly like in the screenshots.

Are you running it in dx11? Do you have anything else in the project?

**Comment by sniffle6** [comment]
Im on Dx11, nothing else in the project, it worked fine in 5.5 and the latest forked version seems to be working fine,  Haven't fully tested threw it tho

**Comment by sniffle6** [comment]
https://gyazo.com/4da42478eed6c1c84d47a6f176e919b7
https://gyazo.com/9460eebe83ec5ba026b88262f01e147d

didnt change anyhting, just downloaded the file opened it and turned the volumetric fog on and off

**Comment by sniffle6** [comment]
i upgraded to b11 just to see if it would work and that current version isnt working. Same as whats shown in the screen shots

https://i.gyazo.com/1c7c9c002b79a689a7c636e99753d971.png
https://i.gyazo.com/80a9c7ffc4c333e76fe6b93b6837d23c.png

**Comment by bjporter** [comment]
Also not working here as well. (tried 5.6.0b8, and 5.6.0f1)

I'm running dx11, and nothing else is going on. Just loaded the default project. No volumetric lights are showing at all.
