### ISSUE TITLE
Directional light?

### ISSUE THREAD

**Issue by k0091601** [Unity-Technologies/VolumetricLighting#8]
Is that Directional light support still in the works?
:)

**Comment by robertcupisz** [comment]
Yes! I'll push it here some time after Unity 2017.1 is released and it will rely on Scriptable Render Pipelines - the HD Render Pipeline specifically.

**Comment by k0091601** [comment]
Still coming? don't forget this feature ! :)

**Comment by robertcupisz** [comment]
Still coming! Lots of other improvements as well, just delayed somewhat.
